# Generated by Django 5.0.7 on 2024-08-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('draft', 'Draft'), ('trash', 'Trash')], default='draft', max_length=20),
        ),
    ]
